# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: vmware
name: vmware
version: 1.0.0
readme: README.md
authors:
  - Ansible Cloud Content Team (@redhat-cop)
description: Collection to manage VMware
license_file: LICENSE
tags:
  - cloud
  - vmware
  - virtualization
repository: https://github.com/ansible-collections/vmware.vmware
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/vmware.vmware
issues: https://github.com/ansible-collections/vmware.vmware/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .github
  - .vscode
